# Generated by Django 3.0.8 on 2020-08-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='status',
        ),
    ]
